/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d8dad9",
        "on-primary-fixed-variant": "#005312",
        "tertiary": "#704d40",
        "on-secondary-fixed": "#001d32",
        "on-primary-container": "#cbffc2",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#603f33",
        "on-secondary-container": "#00436a",
        "on-primary-fixed": "#002204",
        "on-error": "#ffffff",
        "on-background": "#191c1b",
        "error-container": "#ffdad6",
        "surface-container-high": "#e6e9e7",
        "primary": "#0d631b",
        "background": "#f8faf8",
        "tertiary-container": "#8b6557",
        "surface": "#f8faf8",
        "on-tertiary-container": "#ffeee8",
        "on-secondary": "#ffffff",
        "secondary-container": "#51b2fe",
        "secondary-fixed-dim": "#96ccff",
        "on-tertiary-fixed": "#2e150b",
        "surface-tint": "#1b6d24",
        "inverse-primary": "#88d982",
        "surface-container": "#eceeec",
        "inverse-on-surface": "#eff1ef",
        "surface-container-low": "#f2f4f2",
        "tertiary-fixed": "#ffdbcf",
        "outline-variant": "#bfcaba",
        "inverse-surface": "#2e3130",
        "primary-fixed-dim": "#88d982",
        "secondary": "#00639a",
        "on-surface-variant": "#40493d",
        "primary-fixed": "#a3f69c",
        "primary-container": "#2e7d32",
        "secondary-fixed": "#cee5ff",
        "surface-container-highest": "#e1e3e1",
        "outline": "#707a6c",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ebbcac",
        "on-surface": "#191c1b",
        "on-secondary-fixed-variant": "#004a75",
        "surface-bright": "#f8faf8",
        "surface-variant": "#e1e3e1",
        "on-tertiary": "#ffffff",
        "accent": "#00639a"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "md": "24px",
        "lg": "40px",
        "margin-mobile": "16px",
        "xl": "64px",
        "xs": "4px",
        "sm": "12px",
        "margin-desktop": "80px",
        "gutter": "24px",
        "base": "8px"
      },
      "fontFamily": {
        "title-lg": ["Montserrat"],
        "headline-lg-mobile": ["Montserrat"],
        "headline-lg": ["Montserrat"],
        "display-lg": ["Montserrat"],
        "body-lg": ["Montserrat"],
        "label-sm": ["Montserrat"],
        "label-lg": ["Montserrat"],
        "body-md": ["Montserrat"],
        "sans": ["Montserrat", "sans-serif"]
      },
      "fontSize": {
        "title-lg": ["22px", {"lineHeight": "28px", "fontWeight": "500"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "display-lg": ["57px", {"lineHeight": "64px", "letterSpacing": "-0.25px", "fontWeight": "700"}],
        "body-lg": ["16px", {"lineHeight": "24px", "letterSpacing": "0.5px", "fontWeight": "400"}],
        "label-sm": ["11px", {"lineHeight": "16px", "letterSpacing": "0.5px", "fontWeight": "500"}],
        "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.1px", "fontWeight": "500"}],
        "body-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.25px", "fontWeight": "400"}]
      }
    }
  },
  plugins: [],
}
