spring.application.name=ecollajta
spring.config.import=optional:file:.env[.properties]

# PostgreSQL - Neon
spring.datasource.url=jdbc:postgresql://ep-lucky-block-aqh2w2pb-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}

# JWT
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=${JWT_EXPIRATION_TIME}

# CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}

# Server
server.port=${SERVER_PORT:8080}

# Cambia la ruta de acceso al Swagger UI (Por defecto: /swagger-ui.html)
springdoc.swagger-ui.path=/docs

# Cambia la ruta del JSON con la especificación OpenAPI (Por defecto: /v3/api-docs)
springdoc.api-docs.path=/api-json

# Ordena los controladores alfabéticamente
springdoc.swagger-ui.tags-sorter=alpha

# Ordena los métodos (GET, POST, etc.) por su ruta de manera alfabética
springdoc.swagger-ui.operations-sorter=alpha

# Desactiva la barra de búsqueda superior si solo tienes una API
springdoc.swagger-ui.doc-expansion=none

# Muestra la duración del tiempo de respuesta de cada petición de prueba
springdoc.swagger-ui.display-request-duration=true
# Reemplaza con el paquete exacto de tus controladores de Spring
springdoc.packages-to-scan=com.tuempresa.proyecto.controllers

app.encryption.secret-key=${ENCRYPTION_SECRET_KEY}